<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $conf["title"]; ?></title>
<meta name="keywords" content="singular theme, free template, web design, clean, simple, professional, CSS, HTML" />
<meta name="description" content="Singular Theme, free CSS template from templatemo.com" />
<link href="<?php echo $conf["url"]; ?>css/templatemo_style.css" type="text/css" rel="stylesheet" /> 
	
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/jquery.min.js"></script> 
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/jquery.scrollTo-min.js"></script> 
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/jquery.localscroll-min.js"></script> 
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/init.js"></script> 
    
<link rel="stylesheet" href="<?php echo $conf["url"]; ?>css/slimbox2.css" type="text/css" media="screen" /> 
<script type="text/JavaScript" src="<?php echo $conf["url"]; ?>js/slimbox2.js"></script> 
	
<!-- Timestamp: 1236819900 --> 
</head> 
<body> 
<div id="templatemo_header_wrapper">
	<div id="templatemo_header">
    	<div id="site_title">UM framework intro</div>
        <p id="intro_text">UM RESTful MVC framework</p>
        
    </div>
</div>