<div id="home" class="section">

    <ul id="templatemo_menu">

        <div id="install" class="install"><p style="color:red;"> To run your application, please remove or rename install directory </p></div>

        <li><a href="/index/about" class="about"><span>About</span></a></li>
        <li><a href="/index/howto" class="services"><span>How To Start</span></a></li>

        <li class=""><a href="/index/contact" class="contact"><span>Contact</span></a></li>

    </ul>
    <div><p> This page is fast intro for UM framework </p>
        <p> - about: couple words about MVC and REST API</p>
        <p> - how to: some examples how to use</p>
        <p> - contact: developer contact info </p>
    </div>
</div>