<div id="home" class="section">

    
    <div>
        
        
        
        
        <div class=Section1>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;line-height:
150%'><b><span lang=PL style='font-size:18.0pt;line-height:150%'>5 How to use (
Kako koristiti framework )</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;line-height:
150%'><b><span lang=PL style='font-size:18.0pt;line-height:150%'>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=PL>   </span><span lang=SR>Uz pomo&#263;
par primera vide&#263;emo kako se brzo i lako koristi ovaj framework, najlepše
od svega je to što ne trazi nikakvo predznanje i lako može biti prvi framework
koji koristite, dovoljno je osnovno poznavanje OOP PHP programiranja</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>5.1 Konfigurisanje</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>Framework zahteva da se root web
sajta/web aplikacije nalazi u public_html folderu, ovim se sav kod sklanja iz
javnog foldera i nije direktno dostupan preko interneta.</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>Osim toga, framework se može podesavati
na Core (podešavanja vezana za sam framework) i na App (podešavanja bitna za
korisnika koji svoj projekat zasniva na ovom frameworku) nivou i nalaze se
respektivno u core/config, odnosno app/config folderima (s tim što se nazivi
core i app foldera mogu tako&#273;e izmeniti)</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>Još samo ostaje da se podese biblioteke
koje to zahtevaju, odnosno za po&#269;etak je dovoljno podesiti pristupne
podatke na mysql server.</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>5.2 Pravljenje prvog kontrolera</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>Kontroleri se smeštaju u app/controlers
folder, i bitno je da svaki kontroler nasledi glavni kontroler. Podrazumevani
kontroler je index kontroler, hajde da napravimo jedan:</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-indent:28.35pt;line-height:
150%'><span lang=SR><br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#0000BB;background:white'>&lt;?php<br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#007700;background:white'>class&nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>controllers_index&nbsp;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>extends&nbsp;</span><span style='font-size:10.0pt;line-height:
150%;font-family:"Courier New";color:#0000BB;background:white'>Controller<br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#007700;background:white'>{<br>
&nbsp;&nbsp; &nbsp;public&nbsp;function&nbsp;</span><span style='font-size:
10.0pt;line-height:150%;font-family:"Courier New";color:#0000BB;background:
white'>init</span><span style='font-size:10.0pt;line-height:150%;font-family:
"Courier New";color:#007700;background:white'>(&nbsp;)<br>
&nbsp;&nbsp; &nbsp;{<br>
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>$this</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>-&gt;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>setLevel</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>(</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#DD0000;background:white'>&quot;index&quot;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>,&nbsp;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>LEVELS</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>::</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>GET</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>);<br>
&nbsp;&nbsp; &nbsp;}<br>
&nbsp;&nbsp; &nbsp;function&nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>indexAction</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>(&nbsp;)<br>
&nbsp;&nbsp; &nbsp;{<br>
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>$this</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>-&gt;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>Widget</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>[</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#DD0000;background:white'>&quot;home&quot;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>]&nbsp;=&nbsp;new&nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>Widget</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>(</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#DD0000;background:white'>&quot;home&quot;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>);<br>
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>$model
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>=&nbsp;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>$this</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>-&gt;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>loadModel</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>(</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#DD0000;background:white'>&quot;index&quot;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>);<br>
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>$data
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<span
class=apple-converted-space>&nbsp;</span></span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#007700;background:white'>=&nbsp;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#0000BB;
background:white'>$model</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#007700;background:white'>-&gt;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#0000BB;
background:white'>indexModel</span><span style='font-size:10.0pt;line-height:
150%;font-family:"Courier New";color:#007700;background:white'>();<br>
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#FF8000;background:white'>//load&nbsp;views<br>
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>$this</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>-&gt;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>loadView</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>(</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#DD0000;background:white'>&quot;header&quot;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>,&nbsp;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#DD0000;background:white'>&quot;&quot;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>);<br>
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>$this</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>-&gt;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>loadView</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>(</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#DD0000;background:white'>&quot;index&quot;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>,&nbsp;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>$data</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>);<br>
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>$this</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>-&gt;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>loadView</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>(</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#DD0000;background:white'>&quot;footer&quot;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>,&nbsp;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#DD0000;background:white'>&quot;&quot;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>);<br>
&nbsp;&nbsp; &nbsp;}<br>
}<br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#0000BB;background:white'>?&gt;</span><span lang=SR> </span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>Kako framework koristi autoloader, o&#269;ekuje
se da svaka klasa u imenu sadrži naziv foldera u kom se nalazi
„folder_imeKlase“ pa smo tako dobili da se klasa za naš kontroler naziva: „controllers_index“.
Svaki kontroler poseduje init() funkciju i ona sadrži deo koda koji se prvi
startuje i inicijalizuje kontroler. U ovoj funkciji smo podesili ACL nivo
pristupa za našu prvu indexAction metodu.</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>indexAction() metoda je obavezna za
svaki kontroler i ona se poziva ako nije definisana nijedna druga. U našoj
metodi smo napravili jedan widget loader, angažovali model i podatke koje smo
dobili od njega prosledili samo u jedan od tri view-a, koliko ih ovaj kontroler
poziva</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>5.3 Pravljenje prvog modela</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>Pogledajmo sad kako se pravi i šta radi
angažovani model iz prethodnog koda</span></p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;
margin-left:28.35pt;line-height:150%'><span style='font-size:10.0pt;line-height:
150%;font-family:"Courier New";color:#0000BB;background:white'>&lt;?php<br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#007700;background:white'>class&nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>models_index&nbsp;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>extends&nbsp;</span><span style='font-size:10.0pt;line-height:
150%;font-family:"Courier New";color:#0000BB;background:white'>Model<br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#007700;background:white'>{<br>
&nbsp;&nbsp; &nbsp;function&nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>indexModel</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>(&nbsp;)<br>
&nbsp;&nbsp; &nbsp;{<br>
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;return&nbsp;</span><span style='font-size:
10.0pt;line-height:150%;font-family:"Courier New";color:#DD0000;background:
white'>&quot;Hello&quot;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#007700;background:white'>;<br>
&nbsp;&nbsp; &nbsp;}<br>
}<br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#0000BB;background:white'>?&gt;</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>Vidimo opet isti pristup kad je u
pitanju naziv klase i nasledjujemo glavni Model</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>5.4 Tri view-a u jednoj ku&#263;ici</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>Podaci koje vra&#263;a nas model želimo
da prikažemo korisniku i za to koristimo view:</span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>5.4.1 header.phtml</span></p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;
margin-left:28.35pt;line-height:150%'><span style='font-size:10.0pt;line-height:
150%;font-family:"Courier New";color:black;background:white'>&lt;!DOCTYPE&nbsp;html&nbsp;PUBLIC&nbsp;&quot;-//W3C//DTD&nbsp;XHTML&nbsp;1.0&nbsp;Transitional//EN&quot;&nbsp;&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:black'><br>
<span style='background:white'>&lt;html&nbsp;xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;</span><br>
<span style='background:white'>&lt;head&gt;</span><br>
<span style='background:white'>&lt;meta&nbsp;http-equiv=&quot;Content-Type&quot;&nbsp;content=&quot;text/html;&nbsp;charset=utf-8&quot;&nbsp;/&gt;</span><br>
<span style='background:white'>&lt;title&gt;</span></span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#0000BB;
background:white'>&lt;?php<br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#007700;background:white'>echo&nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>$conf</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>[</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#DD0000;background:white'>&quot;title&quot;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>];<br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#0000BB;background:white'>?&gt;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:black;background:white'>&lt;/title&gt;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:black'><br>
<span style='background:white'>&lt;/head&gt;&nbsp;</span><br>
<span style='background:white'>&lt;body&gt;&nbsp;</span><br>
<span style='background:white'>&lt;div&nbsp;id=&quot;header_wrapper&quot;&gt;</span><br>
<span style='background:white'>&nbsp;&nbsp;
&nbsp;&lt;div&nbsp;id=&quot;header&quot;&gt;</span><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&lt;div&nbsp;id=&quot;site_title&quot;&gt;UM&nbsp;framework&nbsp;intro&lt;/div&gt;</span><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp; &nbsp;
&nbsp;&lt;p&nbsp;id=&quot;intro_text&quot;&gt;</span></span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#0000BB;
background:white'>&lt;?php<br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#007700;background:white'>echo&nbsp;isset(</span><span style='font-size:
10.0pt;line-height:150%;font-family:"Courier New";color:#0000BB;background:
white'>$data</span><span style='font-size:10.0pt;line-height:150%;font-family:
"Courier New";color:#007700;background:white'>)&nbsp;?&nbsp;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#0000BB;
background:white'>$data&nbsp;</span><span style='font-size:10.0pt;line-height:
150%;font-family:"Courier New";color:#007700;background:white'>.&nbsp;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#DD0000;
background:white'>&quot;,&nbsp;&quot;&nbsp;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#007700;background:white'>:&nbsp;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#DD0000;
background:white'>&quot;&quot;</span><span style='font-size:10.0pt;line-height:
150%;font-family:"Courier New";color:#007700;background:white'>;<br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#0000BB;background:white'>?&gt;</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:black;background:white'>&nbsp;You&nbsp;use&nbsp;UM&nbsp;RESTful&nbsp;MVC&nbsp;framework&lt;/p&gt;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:black'><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;</span><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp;&lt;/div&gt;</span><br>
<span style='background:white'>&lt;/div&gt;</span></span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>5.4.2 index.phtml</span></p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;
margin-left:.5in;line-height:150%'><span style='font-size:10.0pt;line-height:
150%;font-family:"Courier New";color:black;background:white'>&lt;div&nbsp;id=&quot;templatemo_main_wrapper&quot;&gt;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:black'><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp;&lt;div&nbsp;id=&quot;templatemo_main&quot;&gt;</span><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp; &nbsp;
&nbsp;&lt;div&nbsp;id=&quot;content&quot;&gt;&nbsp;</span><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#0000BB;background:white'>&lt;?php
$widget</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:#007700;background:white'>[</span><span style='font-size:10.0pt;
line-height:150%;font-family:"Courier New";color:#DD0000;background:white'>&quot;home&quot;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>]-&gt;</span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>load</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:#007700;
background:white'>(); </span><span style='font-size:10.0pt;line-height:150%;
font-family:"Courier New";color:#0000BB;background:white'>?&gt;<br>
</span><span style='font-size:10.0pt;line-height:150%;font-family:"Courier New";
color:black;background:white'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:black'><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp; &nbsp;
&nbsp;&lt;/div&gt;&nbsp;</span><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp;&lt;/div&gt;</span><br>
<span style='background:white'>&lt;/div&gt;</span></span></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>5.4.3 footer.phtml</span></p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;
margin-left:28.35pt;line-height:150%'><span style='font-size:10.0pt;line-height:
150%;font-family:"Courier New";color:black;background:white'>&lt;div&nbsp;id=&quot;footer_wrapper&quot;&gt;</span><span
style='font-size:10.0pt;line-height:150%;font-family:"Courier New";color:black'><br>
<span style='background:white'>&nbsp;&nbsp;
&nbsp;&lt;div&nbsp;id=&quot;footer&quot;&gt;</span><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp; &nbsp;
&nbsp;&lt;p&gt;Copyright&nbsp;©&nbsp;2013&nbsp;UM&nbsp;&lt;/p&gt;</span><br>
<span style='background:white'>&nbsp;&nbsp; &nbsp;&lt;/div&gt;</span><br>
<span style='background:white'>&lt;/div&gt;</span><br>
<br>
<span style='background:white'>&lt;/body&gt;</span><br>
<span style='background:white'>&lt;/html&gt;</span></span></p>



<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><b><span lang=SR>5.5 Rezultat</span></b></p>

<p class=MsoNormal style='margin-bottom:12.0pt;text-align:justify;text-indent:
28.35pt;line-height:150%'><span lang=SR>Uz odgovarajuci template u public_html
folderu, dobili smo ovo:</span></p>

<p class=MsoNormal align=center style='margin-bottom:12.0pt;text-align:center;
text-indent:28.35pt;line-height:150%'><span lang=SR><img width=526 height=512
src="/alive.gif"><br>
slika 5.5.1</span></p>

</div>
        
        
        
        
    </div><div><a href="/">Home</a></div>
</div>
 